// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_commerce;

#nullable disable

namespace e_commerce.Migrations
{
    [DbContext(typeof(appdb))]
    partial class appdbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("e_commerce.Models.category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clothing & Apparel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Living"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Books & Stationery"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Automotive Parts & Accessories"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Groceries & Gourmet Foods"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Jewelry & Watches"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pet Supplies"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Baby & Kids"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Art & Crafts"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Musical Instruments"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Travel & Luggage"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Garden & Outdoor"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Fitness & Exercise"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Watches & Accessories"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Party Supplies"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Industrial & Scientific"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Shoes & Footwear"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Seasonal & Holiday Decor"
                        });
                });

            modelBuilder.Entity("e_commerce.Models.product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<int>("quatity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("category_id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("e_commerce.Models.product", b =>
                {
                    b.HasOne("e_commerce.Models.category", "cat")
                        .WithMany("Products")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cat");
                });

            modelBuilder.Entity("e_commerce.Models.category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
